from selenium.webdriver.common.by import By

class CheckoutCartLocators:
    CHECKOUT_BUTTON = (By.XPATH, "//a[contains(@class, 'btn') and contains(text(), 'Checkout')]")
    INPUT_REGISTER_ACCOUNT = (By.XPATH, "//input[@value='register']")
    NEW_CUSTOMER_BUTTON_CONTINUE = (By.XPATH, "//input[@id='button-account']")
    INPUT_FIRST_NAME = (By.XPATH, "//input[@id='input-payment-firstname']")
    INPUT_LAST_NAME = (By.XPATH, "//input[@id='input-payment-lastname']")
    INPUT_EMAIL = (By.XPATH, "//input[@id='input-payment-email']")
    INPUT_TELEPHONE = (By.XPATH, "//input[@id='input-payment-telephone']")
    INPUT_SHIPPING_ADDRESS1 = (By.XPATH, "//input[@id='input-payment-address-1']")
    INPUT_SHIPPING_CITY = (By.XPATH, "//input[@id='input-payment-city']")
    INPUT_SHIPPING_POSTCODE = (By.XPATH, "//input[@id='input-payment-postcode']")
    SELECT_INPUT_SHIPPING_COUNTY = (By.XPATH, "//select[@id='input-payment-country']")
    OPTION_SHIPPING_COUNTY = (By.XPATH, "//option[@value='9' and contains(text(), 'Antigua and Barbuda')]")
    SELECT_INPUT_SHIPPING_REGION = (By.XPATH, "//select[@id='input-payment-zone']")
    OPTION_SHIPPING_REGION = (By.XPATH, "//option[@value='153' and contains(text(), 'Barbuda')]")
    INPUT_PASSWORD = (By.XPATH, "//input[@id='input-payment-password']")
    INPUT_PASSWORD_CONFIRM = (By.XPATH, "//input[@id='input-payment-confirm']")
    INPUT_REGISTER_AGREE = (By.XPATH, "//input[@name='agree']")
    CONTINUE_BUTTON = (By.XPATH, "//input[@id='button-register']")
    MY_ACCOUNT_LINK_DROPDOWN = (By.XPATH, "//a[@title='My Account']")
    FORM_CHECK_LABEL = (By.XPATH, "//div[@id='payment-existing']")
    MY_ACCOUNT_LINK = (By.XPATH, "//a[contains(text(), 'My Account')]")
    EDIT_ACCOUNT_INFORMATION_LINK = (By.XPATH, '//a[contains(text(),"Edit your account information")]')
